version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin           # 自訂資料庫使用者名稱
      POSTGRES_PASSWORD: admin       # 自訂資料庫密碼
      POSTGRES_DB: testdb            # 初始建立的資料庫名稱
    ports:
      - "5432:5432"                  # 將本機的 5432 埠對應到容器的 5432 埠
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata  # 將資料持久化，避免重啟後資料遺失
    restart: unless-stopped
    

volumes:
  pg_data: